server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: activities-service
          uri: lb://activities-service
          predicates:
            - Path=/api/**
            - Path=/likes/**
            - Path=/posts/**

        - id: newsfeed-service
          uri: lb://newsfeed-service
          predicates:
            - Path=/newsfeeds/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

        - id: stock-service
          uri: lb://stock-service
          predicates:
            - Path=/stocks/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
