spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hufsjlee
    username: hufsjlee
    password: 123123
  security:

  jpa:
    database: mysql
    hibernate: # hibernate 사용 설정
      ddl-auto: create #create, alter, drop, truncate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true

# SQL 스크립트를 사용하여 초기 데이터를 데이터베이스에 로드하는 데 사용되는 설정
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql


  mail:
    host: smtp.gmail.com
    port: 587
    username: deepsj1012@gmail.com
    password: tmsjfowgnmhgtzaw
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

app:
   firebase-configuration-file: ./firebaseSecretKey.json
   firebase-bucket: reservationpurchase.appspot.com
jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400